### ISSUE TITLE
Question: Rich Text Editor Features

### ISSUE THREAD

**Issue by do-web** [kazzkiq/CodeFlask#103]
I what to use code flask with simple rte features like bold, italic is that posibile?

**Comment by kazzkiq** [comment]
Sadly no. CodeFlask is aimed to be a simple code editor. For RTE (WYSIWYG) you can take a look at any of those:

https://github.com/ianstormtaylor/slate
https://github.com/jaredreich/pell
https://github.com/summernote/summernote
https://github.com/bustle/mobiledoc-kit
