### ISSUE TITLE
CodeFlask for Calvin-Lisp

### ISSUE THREAD

**Issue by timo-cmd** [kazzkiq/CodeFlask#116]
Hey,

I have built a codeflask extension and ide for my own programming language, that runs on codeflask.
Now my question is.: Can I publish the new IDE under a my-name-license with CodeFlask tagged? 
The IDE supports, code linting, debug and eval functions.

With best regards,

Timo-cmd

**Comment by kazzkiq** [comment]
Hi @timo-cmd,

Glad to see you made good use of CodeFlask!

This lib is licensed under [MIT license](https://github.com/kazzkiq/CodeFlask/blob/master/LICENSE). This means you're free to use, modify and ship CodeFlask even in commercial projects as long as you give credits back to this lib somewhere in your project (e.g. an "About" or "Credits" page, etc).

By "credits" I mean a simple link is enough, [like this section](https://github.com/kazzkiq/CodeFlask#credits--thanks).

**Comment by timo-cmd** [comment]
Hy,

Thanks, I appreciate it very much. 

Regards 

Timo
