### ISSUE TITLE
Question: project status

### ISSUE THREAD

**Issue by petersolopov** [kazzkiq/CodeFlask#118]
Hello @kazzkiq, thanks for the awesome project!

Could you say what status of the CodeFlask is? Some PR's #105, #98 and issues #96, #102 are opened for a very long time. What will be done with them?

It is a nice idea #110 pass external highlighter. It seems to be useful. What do you think about it? Maybe do not completely remove Prima and add build without it (`codeflask-core.js` for example) 

Any way to add or fix something we need the actual tests that runs in the current stable version of node. I did it in #117.

Can I assume that the project is frozen (I hope no) and I need to create fork and do whatever I want? 

I appreciate any feedback.

**Comment by kazzkiq** [comment]
Hi @petersolopov.

The project is not frozen. It just reached a stable status where most features got covered without sacrificing performance and bundle size.

There are however some improvements to be made, like the PRs and Issues you mentioned. And I will take a closer look at them.
