### ISSUE TITLE
Init new CodeFlask and it's all misaligned

### ISSUE THREAD

**Issue by jamesta696** [kazzkiq/CodeFlask#128]
Just decided to try out this library, and it's rendering all misaligned and off screen...
It's almost like I have to manually go and change all the css values.
Am I doing something wrong?

Thanks

![image](https://user-images.githubusercontent.com/14171094/102572209-4dd9da80-40a0-11eb-99be-944b49fbe52a.png)
![image](https://user-images.githubusercontent.com/14171094/102572292-82e62d00-40a0-11eb-9d23-c68fefe3f2eb.png)

**Comment by M1CK431** [comment]
Set the parent style as `position: relative` :wink:

**Comment by jamesta696** [comment]
> Set the parent style as `position: relative` 😉

I had tried that but was still broken and required more CSS changes in order to render properly,
I decided to just go with **HighlightJS**

Thanks for your reply, forgot to close this issue.
