### ISSUE TITLE
How do I change the language of the editor?

### ISSUE THREAD

**Issue by Explosion-Scratch** [kazzkiq/CodeFlask#129]
It seems that once I set it I can't remove codeflask and reset the language. In my case I need a dropdown of languages which alters the syntax highlighting behavior.

**Comment by clsource** [comment]
Maybe with the function `updateLanguage`

https://github.com/kazzkiq/CodeFlask/blob/master/src/codeflask.js#L386

**Comment by Explosion-Scratch** [comment]
Thanks! 😃
