### ISSUE TITLE
Auto-indent on line break

### ISSUE THREAD

**Issue by lol768** [kazzkiq/CodeFlask#62]
Unsure if there's another issue open for this, but it'd be nice if CodeFlask automatically added the same number of indenting characters (tabs/spaces) based on the previous line when hitting <kbd>Enter</kbd>

**Steps to reproduce:**

* Enter the following text:

```
function foo() {
    // cursor is here: █ 
```

* Hit <kbd>Enter</kbd>

**Result**:

* New line starts flush against the LHS

**Expected result:**

* New line is indented 4 spaces per previous line

**Comment by kazzkiq** [comment]
I'm implementing it on the [new version of CodeFlask](https://github.com/kazzkiq/CodeFlask.js/tree/1.0). This is actually one of the last things missing before I publish the new version.

You can check the current status *(aka. me failing miserably to make it work)* here: https://github.com/kazzkiq/CodeFlask.js/blob/1.0/src/codeflask.js#L212

**Comment by lol768** [comment]
Awesome to hear!

**Comment by simonwidjaja** [comment]
Any news on this?

**Comment by kazzkiq** [comment]
Yes. It didn't worked as expected and is in the "TODO" list.

You can check the relevant code here:
https://github.com/kazzkiq/CodeFlask/blob/master/src/codeflask.js#L235-L264

**Comment by lol768** [comment]
Is this supposed to work on https://kazzkiq.github.io/CodeFlask/?

**Comment by kazzkiq** [comment]
@lol768 Yes.
