### ISSUE TITLE
Adding new languages

### ISSUE THREAD

**Issue by aliktab** [kazzkiq/CodeFlask#70]
Hi,

I'm trying to add PHP language but can't figure out how to do it. I Prism I simply have to add appropriate JS script. Here I have to call function with options. But PHP lang description consists not only of options but also script calls. Any ways to do it here?
https://cdnjs.cloudflare.com/ajax/libs/prism/1.14.0/components/prism-php.js

**Comment by yulodl** [comment]
I run into the same problem with json. [Facepalm] Flask bundle prism inside its build output.
You can use `flask.addLanguage('php',  Prism.languages.extend('clike', {...})) ` to make the prism inside flask support php.
