### ISSUE TITLE
Option to disable keyup events

### ISSUE THREAD

**Issue by jacksonGross** [kazzkiq/CodeFlask#76]
Hi there, thanks for the great library!

I think it would be good if we could pass some options to disable keyup events on the editor. There currently isn't a way to turn off tab indentation or auto closing parentheses via this library and I can't remove the event listener either because it is defined anonymously.

**Comment by bradleyjkemp** [comment]
It would be good to be able to control handleSelfClosingCharacters via options the same way handleTabs is done.

**Comment by kazzkiq** [comment]
That's a good point.

I will work on an option do to disable editor capabilities individually, so user may choose what to keep enabled/disabled.
