### ISSUE TITLE
runUpdate / onUpdate callback has wrong scope on initial load

### ISSUE THREAD

**Issue by marcysutton** [kazzkiq/CodeFlask#77]
In an older version of CodeFlask, `onUpdate` would run on the initial update to the textarea. It's still making the call to `runUpdate`, but the initial function scope is wrong so the callback never runs on page load. 

If you log `this` in `runUpdate` on page load it points to `window`...where Codeflask won't find `this.updateCallBack` later on. Once you type in the textarea, the scope is set to the appropriate object.

This is the part of the code that is wrong: https://github.com/kazzkiq/CodeFlask/blob/master/src/codeflask.js#L295

Fix: Change onUpdate to bind the correct scope
```js
updateCode(newCode) {
    // previous code here
    setTimeout(this.runUpdate.bind(this), 1);
}
```

**Comment by kazzkiq** [comment]
Damn, what a bundler. Thanks for the highlight, its now fixed in [`v1.1.1`](https://www.npmjs.com/package/codeflask).
