### ISSUE TITLE
Feature request: areaId option for labeling textarea

### ISSUE THREAD

**Issue by marcysutton** [kazzkiq/CodeFlask#78]
Codeflask generates a textarea without a paired label element, which poses accessibility problems. An easy way to get around it would be to add an `areaId` option to specify an id value for the textarea. That way a label element can be paired with it for screen reader users. 

I'm not sure if this feature previously existed or if someone on my team hacked in their own fix, but it's super easy to add. I've got it working on my local fork and will contribute it back to you as soon as I add it to the tests.

**Comment by kazzkiq** [comment]
I honestly don't remember this feature in the older version, so I guess it was probably a local fix. But will gladly add a PR with this accessibility feature once you get it done!
