### ISSUE TITLE
Field focus

### ISSUE THREAD

**Issue by elalienx** [kazzkiq/CodeFlask#90]
Hi!, there is a way to enable focus on the editor window? So the user can start editing code without clicking on the window first?

**Comment by kazzkiq** [comment]
As of today, no.

You can hack it with some JavaScript, thought:

```js
// Make sure this core executes after CodeFlask
const editorTextArea = document.querySelector('.codeflask__textarea');
editorTextArea.focus();
```

**Comment by elalienx** [comment]
Thanks that was more specific than the method that I was using
` let textarea = document.getElementsByClassName("codeflask__textarea")[0];`
`textarea.focus();`
