### ISSUE TITLE
Add support to readonly

### ISSUE THREAD

**Issue by elalienx** [kazzkiq/CodeFlask#95]
Hi, thanks for the library. I would like to know if there is a way to make the editor read only after initial setup.
Thank in advance.

**Comment by kazzkiq** [comment]
CodeFlask already supports it via `.enableReadonlyMode()` and `disableReadonlyMode()` methods (details on #85).

e.g.:

```js
import CodeFlask from 'codeflask';

const flask = new CodeFlask('#my-selector', { language: 'js' });

// Now your editor is read-only
flask.enableReadonlyMode();

// Now it's available for editing again
flask.disableReadonlyMode();
```
